# 应用基本配置
application:
  name: "My Python App"
  version: 2.1.0
  debug: false
  environment: production
  max_threads: 8
  timeout: 30.5
  features:
    - authentication
    - notifications
    - analytics
    - reporting

# 数据库配置
database:
  host: db.example.com
  port: 5432
  username: admin
  password: s3cr3tP@ss
  database_name: app_db
  use_ssl: true
  connection_pool:
    min_connections: 2
    max_connections: 10
    timeout: 5

# 日志配置
logging:
  level: INFO
  file_path: /var/log/myapp/app.log
  max_size: 10MB
  backup_count: 5
  rotation: # 复杂结构示例
    - time: "00:00"
      action: rotate
    - size: 100MB
      action: compress

# API 端点配置
api_endpoints:
  users: "https://api.example.com/v1/users"
  products: "https://api.example.com/v1/products"
  orders: "https://api.example.com/v1/orders"

# 用户偏好设置
user_preferences:
  default_theme: dark
  language: en-US
  notifications:
    email: true
    push: true
    sms: false
  refresh_interval: 300

# 网络配置
network:
  whitelisted_ips:
    - 192.168.1.1
    - 192.168.1.5
    - 10.0.0.2
  firewall_rules:
    - name: SSH Access
      port: 22
      protocol: tcp
      allowed: true
    - name: HTTP Access
      port: 80
      protocol: tcp
      allowed: true
    - name: Block ICMP
      protocol: icmp
      allowed: false

# 环境变量引用
environment_variables:
  CACHE_DIR: "${HOME}/.cache/myapp"
  TEMP_DIR: "/tmp/${APP_NAME}"

# 多行文本示例
description: |
  这是一个多行文本示例，
  可以包含任意内容。
  
  空行会被保留，
  并且行尾空格也会保留。
  
  非常适合用于长描述。

# 锚点与引用（复用配置）
database_common: &db_common
  port: 5432
  timeout: 10
  ssl: true

production_db:
  <<: *db_common
  host: prod-db.example.com
  username: prod_admin

staging_db:
  <<: *db_common
  host: staging-db.example.com
  username: staging_user